# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  #hints from zabbix manual 3.2 and https://zabbix.com/forum/showthread.php?p=190597
  sudo rpm -ivh http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm
  sudo yum -y install zabbix-server-mysql zabbix-web-mysql
  sudo yum -y install httpd
  sudo service httpd start
  sudo yum -y install mariadb-server mariadb
  sudo systemctl start mariadb.service
  sudo systemctl enable mariadb.service
  echo "Creating zabbix db"
  mysql -uroot -e "CREATE DATABASE IF NOT EXISTS zabbix character set utf8 collate utf8_bin;"
  echo "grant permissions to db"
  mysql -uroot -proot -e "grant all privileges on zabbix.* to zabbix@localhost identified by 'zabbix';"
  # rpm -q zabbix-server-mysql
  zcat /usr/share/doc/zabbix-server-mysql-3.2.6/create.sql.gz | mysql -uzabbix -p zabbix
  
  
  
  
  
  #sudo yum -y --enablerepo=zabbix-deprecated install zabbix-server-mysql
  #sudo yum -y --enablerepo=zabbix-deprecated install zabbix-web-mysql
  #sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
  #sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
  
  #mysql -uroot -p
  #mysql> create database zabbix character set utf8 collate utf8_bin;
  #mysql> grant all privileges on zabbix.* to zabbix@localhost identified by 'Asap1234';
  #mysql> quit;
  #zcat /usr/share/doc/zabbix-server-mysql-3.2.6/create.sql.gz | mysql -uzabbix -p zabbix
  #vi /etc/zabbix/zabbix_server.conf
  #cp /usr/share/doc/zabbix-web-3.2.6/httpd22-example.conf /etc/httpd/conf.d/zabbix.conf
  #yum install zabbix-agent
  #mysqldump -u root -p --opt zabbix > zabbix_20170707.sql
  #zcat zabbix_20170707.sql.gz | mysql -u root -p zabbix
  #service zabbix-agent start
  #service zabbix-server start
  #service httpd restart

  SHELL
end
