# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.box = "C:/Vagrant_boxes/Windows_Server_2012_R2.box"
	config.vm.guest = :windows
	config.vm.communicator = "winrm"
	config.vm.boot_timeout = 600
	config.vm.graceful_halt_timeout = 600
	config.vm.network :forwarded_port, guest: 3389, host: 3390
	config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
	config.winrm.username = "Administrator"
	config.winrm.password = "Asap1234"
	config.vm.network "private_network", ip: "192.168.33.10"
	config.vm.provider "virtualbox" do |vb|
	#   # Display the VirtualBox GUI when booting the machine
		vb.name = "Windows_Server_2012_R2 Vagrant"
		#vb.group = "TEST"
		vb.gui = true
		vb.memory = "1024"
	end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
